server:
  port: 8090

spring:
  application:
    name: loans
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2355/loans_db
    username: developer
    password: 01092209
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: none
      show-sql: false
  flyway:
    locations:
      filesystem: src/main/resources/db/migration
